version: 0.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - InitialCommit
image: Visual Studio 2019
configuration: Release
platform: Any CPU
before_build:
- cmd: dotnet restore
build:
  project: ServiceResolution.sln 
  verbosity: detailed
artifacts:
- path: \**\*.nupkg
deploy:
  provider: NuGet
  server: https://ci.appveyor.com/nuget/configureappio-q2ljbk9rvmw3/api/v2/package                 # remove to push to NuGet.org
  api_key: 
    secure: wAI3TuSCRM9dlaPnEdjLfkaMFC0C27DEFWTekTbyw7Y=
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/

notifications:
- provider: Email
  to:
  - appveyor@configureapp.io
  subject: AppVeyor Build Notification
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true