version: 0.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - InitialCommit
build:
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
notifications:
- provider: Email
  to:
  - appveyor@configureapp.io
  subject: AppVeyor Build Notification
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true